jobs:
  - job: JobOne
    steps:
      - task: Bash@3.201.1
        inputs:
          script: 'echo Hello World'

      - task: AzureFileCopy@1

  - job: JobTwo
    steps:
      - task: AzureCLI@1

      - task: AzureCLI@2
