jobs:
  - job: JobOne
    steps:
      - task: Bash@3
        inputs:
          script: 'echo Hello World'

      - task: AzureFileCopy@1

  - job: JobTwo
    steps:
      - task: AzureCLI@2.198.0

      - task: AzureCLI@2.198.0
