jobs:
  - job: JobOne
    steps:
      - task: Bash@3
        inputs:
          script: 'echo Hello World'

      - task: AzureFileCopy@5.208.0

  - job: JobTwo
    steps:
      - task: AzureCLI@1

      - task: AzureCLI@2
